### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by kkiyama117** [boil-ninjin/Graphillion#1]
# 概要
Pythonにおける幾つかのtipsをば。
Issueの使い方も兼ねて。

## Issue
課題、等といった意味にあたるが、名前そのまま改善したいことやBugの修正等の提起や議論に用いられる。PullRequestの方でも同様な議論が出来るが、違いとしてあちらは変更元、変更先のブランチと紐付いており、承認することでコードをMergeできる事から具体的な修正や新規コードについての具体的な議論に使われることがほとんどである。対照的にissueはまだ実装されていないコードについてや、新しい概念やそれの実装手法等のより抽象的な話がなされる事が多い。

### close
終了した、完了した、と思われる課題はその理由が肯定的であろうと否定的であろうと「close」する事が出来る。こうすることでissue一覧のデフォルトの画面から消えるが、よく見るとこの画面には「open」というフィルターがあることを確認できると思う。つまりこれを消すことでcloseされたissueも表示することが出来るし、他にもcloseされたもののみ確認するなど、(少なくともあなたが思う以上に)様々な検索が出来る。これはPull requestsにおいても同様である。

## 本題(Python)
端的にいうと
- Linterを入れよう
- 拡張機能を入れて補完出来るようにしよう
- (もし出来るなら)classやモジュールを使って適切にコードを設計しよう

の3点。上2つはすぐ出来るが最後のものは鍛錬が要る。しかし、実用ではなく理論や研究に用いられるコードは、特にどこぞやの記事に「コードの設計の不備を理論的な才能でゴリ押して動かしている」と皮肉られる位には設計がない。 要するに理論だけ書ければ良く、適切な情報理論やコードを書く言語の思想、読み手や使い手への配慮をしない学者が世には多い、ということである。個人的に幾つか他人の研究を手伝わされた身としては、これが出来ているだけで大きな差別点になりうると思う。「ダメなコード」は結局自分で似たものに使い回したい、と思っても一から書き直す事になるが、「適切なコード」は他人だけでなく自分にとっても「再利用可能」かつ思考を伝える手段としても大きな武器になると思う。

具体的な方法だが、上2つはググればすぐに分かる。
最後のものは定期的にコードを書く、良質なコードを読む(request等のよく使われるライブラリのコード等が良いと思うが、一方で普遍性の為に複雑な設計や黒魔術のような上級者向けhackを含む事が多いのでその辺りを注意して読むと良い)、等があるが、Pythonの公式や[zen of python](https://qiita.com/IshitaTakeshi/items/e4145921c8dbf7ba57ef),[ヒッチハイカーズガイド](https://python-guideja.readthedocs.io/ja/latest/) 等のドキュメントとlinter及びformatterの出力するwarningを読み、それを地道に修正する(嬉しいことに今のエディタはそれをワンクリックで修正してくれる！)ことでも身についていくと思う。

**Comment by kkiyama117** [comment]
補足ですがいまんとこ大丈夫だと思います、コードややることが複雑になったら気をつけてね、ってだけのやつ

**Comment by mirinrimi** [comment]
やったね

**Comment by kkiyama117** [comment]
今後もコツコツと楽しくコードを書こう
